---
abstract: 'Parse directory listing'
author:
  - 'Gisle Aas'
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Test::More: '0.98'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Listing
no_index:
  directory:
    - maint
requires:
  Carp: '0'
  Exporter: '0'
  HTTP::Date: '0'
  Time::Local: '0'
  base: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/PerlAlien/File-Listing/issues
  homepage: https://metacpan.org/pod/File::Listing
  repository: git://github.com/PerlAlien/File-Listing.git
version: '6.14'
x_contributors:
  - 'Gisle Aas'
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Adam Kennedy'
  - 'Adam Sjogren'
  - 'Alex Kapranoff'
  - 'Alexey Tourbin'
  - 'Andreas J. Koenig'
  - 'Bill Mann'
  - 'Bron Gondwana'
  - DAVIDRW
  - 'Daniel Hedlund'
  - 'David E. Wheeler'
  - 'David Steinbrunner'
  - 'Erik Esterer'
  - FWILES
  - 'Father Chrysostomos'
  - 'Gavin Peters'
  - 'Graeme Thompson'
  - 'Hans-H. Froehlich'
  - 'Ian Kilgore'
  - 'Jacob J'
  - 'Mark Stosberg'
  - 'Mike Schilli'
  - 'Ondrej Hanak'
  - 'Peter John Acklam'
  - 'Peter Rabbitson'
  - 'Robert Stone'
  - 'Rolf Grossmann'
  - 'Sean M. Burke'
  - 'Simon Legner'
  - 'Slaven Rezic'
  - 'Spiros Denaxas'
  - 'Steve Hay'
  - 'Todd Lipcon'
  - 'Tom Hukins'
  - 'Tony Finch'
  - 'Toru Yamaguchi'
  - 'Ville Skyttä'
  - 'Yuri Karaban'
  - Zefram
  - amire80
  - jefflee
  - john9art
  - mschilli
  - murphy
  - phrstbrn
  - ruff
  - sasao
  - uid39246
x_generated_by_perl: v5.33.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_use_unsafe_inc: 0
