---
abstract: 'Read data from __DATA__'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: '0.88'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Section-Simple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/Data-Section-Simple/issues
  homepage: https://github.com/miyagawa/Data-Section-Simple
  repository: https://github.com/miyagawa/Data-Section-Simple.git
version: '0.07'
x_contributors:
  - 'Bruce Gray <bruce.gray@acm.org>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
