---
abstract: 'Middleware for session management'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  HTTP::Cookies: '0'
  HTTP::Request::Common: '0'
  LWP::UserAgent: '0'
  Test::Fatal: '0.006'
  Test::More: '0.88'
  Test::Requires: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.20, Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-Session
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Cookie::Baker: '0.10'
  Digest::HMAC_SHA1: '1.03'
  Digest::SHA: '0'
  Plack: '0.9910'
resources:
  bugtracker: https://github.com/plack/Plack-Middleware-Session/issues
  homepage: https://github.com/plack/Plack-Middleware-Session
  repository: https://github.com/plack/Plack-Middleware-Session.git
version: '0.33'
x_contributors:
  - 'Alex Vandiver <alex@chmrr.net>'
  - 'Florian Schlichting <fsfs@debian.org>'
  - 'franck cuny <franck@lumberjaph.net>'
  - 'Graham Knop <gknop@omniti.com>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Ivan Baidakou <basiliscos@openmailbox.com>'
  - 'James E Keenan <jkeenan@cpan.org>'
  - 'John Lifsey <john.lifsey@inspire.com>'
  - 'Lee Aylward <lee@laylward.com>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
  - 'Masahiro Chiba <chiba@geminium.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 's-aska <s.aska.org@gmail.com>'
  - 'Stevan Little <stevan.little@iinteractive.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'vividsnow <vividsnow@gmail.com>'
x_generated_by_perl: v5.20.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_static_install: 1
