---
abstract: 'Get information about a class and its structure'
author:
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: '0.98'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Inspector
provides:
  Class::Inspector:
    file: lib/Class/Inspector.pm
    version: '1.36'
  Class::Inspector::Functions:
    file: lib/Class/Inspector/Functions.pm
    version: '1.36'
requires:
  File::Spec: '0.80'
  base: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/plicease/Class-Inspector/issues
  homepage: https://metacpan.org/pod/Class::Inspector
  repository: git://github.com/plicease/Class-Inspector.git
version: '1.36'
x_contributors:
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Tom Wyant'
  - 'Steffen Müller'
  - 'Kivanc Yazan (KYZN)'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_use_unsafe_inc: 0
