---
abstract: 'A simple prefork server framework'
author:
  - 'Kazuho Oku'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Requires: 0
  Test::SharedFork: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Parallel::Prefork
name: Parallel-Prefork
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Lite: 0.04
  List::MoreUtils: 0
  Proc::Wait3: 0.03
  Scope::Guard: 0
  Signal::Mask: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: '0.18'
