---
abstract: 'Simple DBI wrapper'
author:
  - 'Masahiro Nagano <kazeburo KZBRKZBR@ gmail.com>'
build_requires:
  Capture::Tiny: '0'
  Test::Exception: '0'
  Test::More: '0.98'
  Test::Requires: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.10, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Sunny
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DBIx::Sunny:
    file: lib/DBIx/Sunny.pm
    version: '0.9992'
  DBIx::Sunny::Schema:
    file: lib/DBIx/Sunny/Schema.pm
  DBIx::Sunny::Util:
    file: lib/DBIx/Sunny/Util.pm
  DBIx::Sunny::db:
    file: lib/DBIx/Sunny.pm
  DBIx::Sunny::st:
    file: lib/DBIx/Sunny.pm
requires:
  Class::Accessor::Lite: '0.05'
  Class::Data::Inheritable: '0'
  DBI: '1.615'
  DBIx::TransactionManager: '0.13'
  Data::Validator: '0'
  SQL::Maker::SQLType: '0'
  SQL::NamedPlaceholder: '0.10'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/kazeburo/DBIx-Sunny/issues
  homepage: https://github.com/kazeburo/DBIx-Sunny
  repository: git://github.com/kazeburo/DBIx-Sunny.git
version: '0.9992'
x_authority: cpan:KAZEBURO
x_contributors:
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Songmu <y.songmu@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'egawata <egawa.takashi@gmail.com>'
  - 'motemen <motemen@gmail.com>'
  - 'nanto_vi <nanto@moon.email.ne.jp>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
