--- #YAML:1.0
name:               WWW-RobotRules
version:            6.02
abstract:           database of robots.txt-derived permissions
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyDBM_File:  0
    Fcntl:        0
    perl:         5.008001
    URI:          1.10
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/www-robotrules
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
