---
abstract: 'cPanel fork of JSON::XS, fast and correct serializing'
author:
  - 'Reini Urban <rurban@cpan.org>'
build_requires:
  B: '0'
  Config: '0'
  Data::Dumper: '0'
  Devel::Peek: '0'
  Encode: '1.9801'
  ExtUtils::MakeMaker: '0'
  POSIX: '0'
  Test: '0'
  Test::More: '0'
  Tie::Array: '0'
  Tie::Hash: '0'
  Time::Piece: '0'
  charnames: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.38, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cpanel-JSON-XS
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigFloat: '1.16'
  Math::BigInt: '0'
requires:
  Carp: '0'
  Encode: '1.9801'
  Exporter: '0'
  Pod::Text: '2.08'
  XSLoader: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/rurban/Cpanel-JSON-XS/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rurban/Cpanel-JSON-XS
version: '4.26'
x_contributors:
  - 'Ashley Willis <ashleyw@cpan.org>'
  - 'Chip Salzenberg <chip@pobox.com>'
  - 'Christopher J. Madsen <cjm@cjmweb.net>'
  - 'Colin Kuskie <colink@perldreamer.com>'
  - 'Daniel Dragan <bulk88@hotmail.com>'
  - 'David Golden <xdg@xdg.me>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'E. Choroba <choroba@users.noreply.github.com>'
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
  - 'Gilmar Santos Jr <jgasjr@gmail.com>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'James Rouzier <rouzier@gmail.com>'
  - 'J. Nick Koston <nick@cpanel.net>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Lubomir Rintel <lkundrak@v3.sk>'
  - 'Lukas Mai <l.mai@web.de>'
  - 'Matthew Horsfall <wolfsage@gmail.com>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Pali <pali@cpan.org>'
  - 'Patrick Cronin <PatrickCronin@users.noreply.github.com>'
  - 'Quim Rovira <quim@rovira.cat>'
  - 'Sergey Aleynikov <sergey.aleynikov@gmail.com>'
  - 'Syohei Yoshida <syohex@gmail.com>'
  - 'tevfik1903 <tevfik1903@users.noreply.github.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
