name = "Mouse"
badges = ["travis"]
allow_pureperl = 1
module_maker = "ModuleBuild"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ["t", "xt", "tool", "author", "example", "benchmarks", "builder"]

[ReleaseTest]
MinimumVersion = false

[FileGatherer]
exclude_match = ["^Moose-t-failing", "^xt", "^author", "^TODO$"]
