/**
 * Generated from Config::AutoConf
 *
 * Do not edit this file, all modifications will be lost,
 * modify Makefile.PL or Build.PL instead.
 *
 * Inspired by GNU AutoConf.
 *
 * (c) 2011 Alberto Simoes & Jens Rehsack
 */
#ifndef __CONFIG_H__

/* defined when ssize_t is available */
#define HAVE_SSIZE_T 1
/* defined when inttypes.h is available */
#define HAVE_INTTYPES_H 1
/* defined when stdarg.h is available */
#define HAVE_STDARG_H 1
/* defined when memory.h is available */
#define HAVE_MEMORY_H 1
/* defined when ctype.h is available */
#define HAVE_CTYPE_H 1
/* Defined when feature statement expression is available */
/* #undef HAVE_FEATURE_STATEMENT_EXPRESSION */

/* defined when stdint.h is available */
#define HAVE_STDINT_H 1
/* defined when string.h is available */
#define HAVE_STRING_H 1
/* defined when sys/time.h is available */
#define HAVE_SYS_TIME_H 1
/* defined when sys/stat.h is available */
#define HAVE_SYS_STAT_H 1
/* defined when locale.h is available */
#define HAVE_LOCALE_H 1
/* defined when time.h is available */
#define HAVE_TIME_H 1
/* defined when signal.h is available */
#define HAVE_SIGNAL_H 1
/* Defined when builtin expect is available */
/* #undef HAVE_BUILTIN_EXPECT */

/* defined when float.h is available */
#define HAVE_FLOAT_H 1
/* defined when stdlib.h is available */
#define HAVE_STDLIB_H 1
/* defined when math.h is available */
#define HAVE_MATH_H 1
/* defined when stddef.h is available */
#define HAVE_STDDEF_H 1
/* defined when limits.h is available */
#define HAVE_LIMITS_H 1
/* defined when stdio.h is available */
#define HAVE_STDIO_H 1
/* defined when unistd.h is available */
#define HAVE_UNISTD_H 1
/* defined when sys/types.h is available */
#define HAVE_SYS_TYPES_H 1
/* Defined when time is available */
#define HAVE_TIME 1
/* defined when errno.h is available */
#define HAVE_ERRNO_H 1
/* defined when setjmp.h is available */
#define HAVE_SETJMP_H 1
/* defined when size_t is available */
#define HAVE_SIZE_T 1
/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
/* defined when assert.h is available */
#define HAVE_ASSERT_H 1
/* defined when strings.h is available */
#define HAVE_STRINGS_H 1
#endif /* ?__CONFIG_H__ */
