---
abstract: 'Provide the stuff missing in List::Util'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Storable: '0'
  Test::LeakTrace: '0'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: List-MoreUtils
no_index:
  directory:
    - t
    - inc
requires:
  Exporter::Tiny: '0.038'
  List::MoreUtils::XS: '0.430'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=List-MoreUtils
  homepage: https://metacpan.org/release/List-MoreUtils
  repository: https://github.com/perl5-utils/List-MoreUtils.git
version: '0.430'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
