---
abstract: 'HTML parser class'
author:
  - 'Gisle Aas <gaas@cpan.org>'
build_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FileHandle: '0'
  IO::File: '0'
  SelectSaver: '0'
  Test: '0'
  Test::More: '0'
  URI: '0'
  perl: '5.008'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.52'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Parser
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  HTML::Entities:
    file: lib/HTML/Entities.pm
    version: '3.76'
  HTML::Filter:
    file: lib/HTML/Filter.pm
    version: '3.76'
    x_deprecated: 1
  HTML::HeadParser:
    file: lib/HTML/HeadParser.pm
    version: '3.76'
  HTML::LinkExtor:
    file: lib/HTML/LinkExtor.pm
    version: '3.76'
  HTML::Parser:
    file: lib/HTML/Parser.pm
    version: '3.76'
  HTML::PullParser:
    file: lib/HTML/PullParser.pm
    version: '3.76'
  HTML::TokeParser:
    file: lib/HTML/TokeParser.pm
    version: '3.76'
requires:
  Carp: '0'
  Exporter: '0'
  HTML::Tagset: '0'
  HTTP::Headers: '0'
  IO::File: '0'
  URI: '0'
  URI::URL: '0'
  XSLoader: '0'
  perl: '5.008'
  strict: '0'
resources:
  bugtracker: https://github.com/libwww-perl/HTML-Parser/issues
  homepage: https://github.com/libwww-perl/HTML-Parser
  repository: https://github.com/libwww-perl/HTML-Parser.git
version: '3.76'
x_contributors:
  - 'Antonio Radici <antonio@dyne.org>'
  - 'Barbie <barbie@missbarbell.co.uk>'
  - 'bulk88 <bulk88@hotmail.com>'
  - 'Chase Whitener <capoeirab@cpan.org>'
  - 'Chip Salzenberg <chip@pobox.com>'
  - 'Damyan Ivanov <dmn@debian.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'François Perrad <francois.perrad@gadz.org>'
  - 'Gisle Aas <gisle@aas.no>'
  - 'Jacques Germishuys <jacquesg@striata.com>'
  - 'Jon Jensen <jon@endpoint.com>'
  - 'Mike South <msouth@gmail.com>'
  - 'Nicholas Clark <nick@ccl4.org>'
  - 'Nicolas R <nicolas@atoomic.org>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Salvatore Bonaccorso <salvatore.bonaccorso@gmail.com>'
  - 'Todd Rinaldo <toddr@cpan.org>'
  - 'Ville Skyttä <ville.skytta@iki.fi>'
  - 'Yves Orton <demerphq@gmail.com>'
  - 'Zefram <zefram@fysh.org>'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
