---
abstract: 'JSON Web Token'
author:
  - 'Karel Miko'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.60, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-JWT
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Raw::Zlib: '0'
  CryptX: '0.067'
  Exporter: '5.57'
  JSON: '0'
  Scalar::Util: '0'
  Test::More: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/DCIT/perl-Crypt-JWT/issues
  repository: https://github.com/DCIT/perl-Crypt-JWT
version: '0.033'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
