---
abstract: 'Verify requirements in a CPAN::Meta object'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  CPAN::Meta: '2.120920'
  Env: '0'
  Test::Deep: '0'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Meta-Check
provides:
  CPAN::Meta::Check:
    file: lib/CPAN/Meta/Check.pm
    version: '0.014'
requires:
  CPAN::Meta::Prereqs: '2.132830'
  CPAN::Meta::Requirements: '2.121'
  Exporter: '0'
  Module::Metadata: '1.000023'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Meta-Check
  repository: git://github.com/Leont/cpan-meta-check.git
version: '0.014'
x_contributors:
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Leon Timmermans <fawaka@gmail.com>'
x_serialization_backend: 'YAML::Tiny version 1.69'
