--- #YAML:1.0
name:               HTTP-Negotiate
version:            6.01
abstract:           choose a variant to serve
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Headers:  6
    perl:           5.008001
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/http-negotiate
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
