---
abstract: 'Perl extension for formatting numbers'
author:
  - 'William R. Ward <wrw@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Format
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  POSIX: 0
resources:
  bugtracker: https://rt.cpan.org/NoAuth/Bugs.html?Dist=Number-Format
  repository: https://github.com/billward/number-format-perl.git
version: 1.75
