---
abstract: 'File path utility'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Digest::MD5: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0.86'
  File::Spec::Functions: '0'
  File::Spec::Unix: '0'
  File::Temp: '0.19'
  Test::More: '0.96'
  lib: '0'
  open: '0'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Path-Tiny
no_index:
  directory:
    - corpus
    - examples
    - t
    - xt
  package:
    - DB
    - flock
provides:
  Path::Tiny:
    file: lib/Path/Tiny.pm
    version: '0.118'
  Path::Tiny::Error:
    file: lib/Path/Tiny.pm
    version: '0.118'
recommends:
  Unicode::UTF8: '0.58'
requires:
  Carp: '0'
  Cwd: '0'
  Digest: '1.03'
  Digest::SHA: '5.45'
  Encode: '0'
  Exporter: '5.57'
  Fcntl: '0'
  File::Copy: '0'
  File::Glob: '0'
  File::Path: '2.07'
  File::Spec: '0.86'
  File::Temp: '0.19'
  File::stat: '0'
  constant: '0'
  overload: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
  warnings::register: '0'
resources:
  bugtracker: https://github.com/dagolden/Path-Tiny/issues
  homepage: https://github.com/dagolden/Path-Tiny
  repository: https://github.com/dagolden/Path-Tiny.git
version: '0.118'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Alex Efros <powerman@powerman.name>'
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Chris Williams <bingos@cpan.org>'
  - 'Dan Book <grinnz@grinnz.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Doug Bell <madcityzen@gmail.com>'
  - 'Gabor Szabo <szabgab@cpan.org>'
  - 'Gabriel Andrade <gabiruh@gmail.com>'
  - 'George Hartzell <hartzell@cpan.org>'
  - 'Geraud Continsouzas <geraud@scsi.nc>'
  - 'Goro Fuji <gfuji@cpan.org>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Ian Sillitoe <ian@sillit.com>'
  - 'James Hunt <james@niftylogic.com>'
  - 'John Karr <brainbuz@brainbuz.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Mark Ellis <mark.ellis@cartridgesave.co.uk>'
  - 'Martin H. Sluka <fany@cpan.org>'
  - 'Martin Kjeldsen <mk@bluepipe.dk>'
  - 'Michael G. Schwern <mschwern@cpan.org>'
  - 'Nigel Gregoire <nigelgregoire@gmail.com>'
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
  - 'regina-verbae <regina-verbae@users.noreply.github.com>'
  - 'Roy Ivy III <rivy@cpan.org>'
  - 'Shlomi Fish <shlomif@shlomifish.org>'
  - 'Smylers <Smylers@stripey.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
  - '김도형 - Keedi Kim <keedi@cpan.org>'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Apache-2.0
